version: 2

jobs:
  deploy:
    docker:
      - image: totakoko/compose-deploy-ci:42c2bcef14ffd1c774039f03a2a8b446b1aa2977
    steps:
      - checkout
      - run:
          command: compose-deploy deploy

workflows:
  version: 2
  commit:
    jobs:
      - deploy:
          requires: []