version: 2

jobs:
  deploy:
    docker:
      - image: totakoko/compose-deploy-ci:master
    steps:
      - checkout
      - run:
          command: compose-deploy deploy

workflows:
  version: 2
  commit:
    jobs:
      - deploy:
          requires: []