version: 2

jobs:
  deploy:
    docker:
      - image: totakoko/compose-deploy-ci:df0116278d07027e72ea31d5ff05e3fb6e88fecf
    steps:
      - checkout
      - run:
          command: compose-deploy deploy

workflows:
  version: 2
  commit:
    jobs:
      - deploy:
          requires: []