version: '3'

services:
  server:
    image: alpine
    restart: unless-stopped
    command: ash -c 'while true ; do echo -e "HTTP/1.1 200 OK\n\n$${CONTENT:-It works!}" | nc -l -p 5000; done'
    environment:
      - CONTENT=db74970551014941e05148cba1d97f5aa75beded-2020-07-12T13:16:06+0000
    ports:
      - 8500:5000